---
title: "Extract data"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r prepare}
library(rvest)
library(dplyr, warn.conflicts = FALSE)

dir.create(here::here("data", "attrs"), recursive = TRUE, showWarnings = FALSE)
```

```{r}
datalist_files <- list.files(here::here("data-raw", "datalist"), full.names = TRUE)
id <- stringr::str_replace(basename(datalist_files), "(?:KsjTmplt-)(.*?)(?:-v.*)?(?:\\.html)", "\\1")

idx_exclude <- id %in% c("C23", "A09", "A20", "A31", "S10a")
datalist_files <- datalist_files[!idx_exclude]
id <- id[!idx_exclude]

names(datalist_files) <- id

tables <- purrr::map(datalist_files, ~ {
  read_html(.x) %>% 
    html_table() %>% 
    purrr::keep(~ "地物情報" == colnames(.x)[1])
})

# テーブル一つだけなことを確認
stopifnot(all(lengths(tables) == 1L))

# 確認したら、アクセスしやすくするために一段階減らす
tables <- purrr::map(tables, 1L)
```

属性情報をもたないテーブルは取り除く

```{r}
no_attr_info <- names(tables)[purrr::map_lgl(tables, ~ !"属性情報" %in% .x[[1]])]
no_attr_info

id <- id[!id %in% no_attr_info]
tables <- tables[!names(tables) %in% no_attr_info]
```

```{r}
tables <- tables %>% 
  purrr::imap(~ {
    # 属性情報の行だけにする
    .x <- .x[startsWith(.x[[1]], "属性情報"), , drop = FALSE]
    # 1行目はヘッダ
    nm <- .x[1, ]
    .x <- .x[-1, ]
    colnames(.x) <- nm
    # すべてNAの列は取り除く
    idx <- purrr::map_lgl(.x, ~ any(!is.na(.)))
    .x[, idx]
  })
```

属性情報の行が1行だけのテーブルも取り除く

```{r}
no_rows <- names(tables)[purrr::map_lgl(tables, ~ nrow(.x) == 0)]
no_rows

id <- id[!id %in% no_rows]
tables <- tables[!names(tables) %in% no_rows]
```


カラム数は4のはずだが、ちがうやつがある。この辺はあとで個別に処理することにする。

```{r more_columns}
names(tables)[lengths(tables) != 4L]

tables <- tables[lengths(tables) == 4L]
```

```{r}
# 2番めの列が「属性名」または「属性名（...）」のようなフォーマットであることを確認
stopifnot(all(startsWith(purrr::map_chr(tables, ~ colnames(.)[2]), "属性名")))

tables %>% 
  purrr::iwalk(~ {
    .x %>% 
      tidyr::extract(2, into = c("name", "code"), regex = "([^（]*)(（.*）)?") %>% 
      transmute(
        name,
        code = if_else(code != '', stringr::str_remove_all(code, "[（）]"), NA_character_),
        description = 説明,
        type = 属性の型
      ) %>%
      readr::write_csv(here::here("data", "attrs", glue::glue("{.y}.csv")))
  })
```



