---
title: "Validate extracted data"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r prepare}
library(readr)
library(dplyr, warn.conflicts = FALSE)
```

```{r read}
csv_files <- list.files(here::here("data", "attrs"), full.names = TRUE)
names(csv_files) <- tools::file_path_sans_ext(basename(csv_files))

col_types <- cols(
  name = col_character(),
  code = col_character(),
  description = col_character(),
  type = col_character()
)
d <- purrr::map_dfr(csv_files, read_csv, col_types = col_types, .id = "id")
```

## `code`

変なコードが紛れ込んでいないのを目視確認。

```{r uniq_code}
unique(d$code)
```

コード欠損率を表示。

```{r}
d %>% 
  group_by(id) %>% 
  summarise(
    n = n(),
    missing_rate = scales::percent(sum(is.na(code)) / n(), accuracy = 0.1)
  ) %>% 
  knitr::kable()
```

### `A22-m`, `A34`, `A35a`, `A35b`, `A37`, `P15`, `P16`, `P17`, `P18`, 

ルールに従って展開する必要がある。あとで個別対応。

```{r A22-m}
d %>% 
  filter(id == "A22-m", is.na(code)) %>% 
  head() %>% 
  knitr::kable()
```

### `L03-a`

複雑そう。あとで個別対応。

```{r L03-a}
d %>% 
  filter(id == "L03-a") %>% 
  pull(name)
```

### `mesh1000`, `mesh500`

年代層によって後ろに`A`〜`D`がつく（説明と違って実際には `_` はないみたい）。これもあとで個別対応。
あと、ここはファイル名が`mesh1000`ではなく`m1000`になってるっぽいのでそこも対応が必要かも。

```{r mesh1000}
d %>% 
  filter(id == "mesh1000") %>% 
  slice(3:4) %>% 
  glimpse()
```

### `P21`

`-`と`_`の打ち間違いっぽい。そして実際のカラム名は`P21A_001`のようになっていて、`P21`のあとに付くアルファベットが大文字な点にも注意。

```{r P21}
d %>% 
  filter(id == "P21") %>% 
  knitr::kable()
```

### `N05`

なにやら特殊ルールがあるっぽい。

```{r N05}
d %>%
  filter(id == "N05") %>%
  slice(5) %>% 
  glimpse()
```


## `type`

```{r type}
d %>% 
  count(
    type = case_when(
      stringr::str_detect(type, "^文字列?型")    ~ "character",
      stringr::str_detect(type, "^整数値?型")    ~ "integer",
      type == "数値型（Integer）"                ~ "integer",
      stringr::str_detect(type, "^実数型")       ~ "double",
      type == "数値型（Decimal）"                ~ "double",
      type == "十進数型（Decimal）"              ~ "double",
      # 時間型は、実際の数字が何桁かで場合分けする必要がありそう（4桁なら年なのでそのまま？、8桁ならDateに変換？）
      stringr::str_detect(type, "^(時間|日付)型") ~ "date_or_year",
      # 順序型は、本来は時刻の日時部分だけだが、これだけ対応するにはちょっと特殊すぎる気がするので character で残す
      stringr::str_detect(type, "^順序型")       ~ "character",
      type == "西暦年4桁、月2桁、日2桁で表す数字8文字" ~ "time",
      # 「コードリスト」は数値型だったりもする（e.g. P16）ので、どの位置でも「コードリスト」が出てくればコードリストとみなす
      stringr::str_detect(type, "コードリスト")  ~ "codelist",
      stringr::str_detect(type, "(行政|参照資料|産廃施設|都道府県|特別管理|不燃領域率定義|防災再開発促進地区指定)コード") ~ "codelist",
      # L03-b-c
      type == "都市地域=1都市地域外=0" ~ "codelist",
      stringr::str_detect(type, "^列挙型")       ~ "factor",
      stringr::str_detect(type, "^真偽値型")     ~ "logical",
      stringr::str_detect(type, "^論理型")       ~ "logical",
      type %in% c("タイプ型「調査内容」") ~ "character",
      TRUE ~ type
    ),
    sort = TRUE
  )
```

