---
title: "Extract codelist"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r check}
library(readr)
library(stringr)
library(dplyr, warn.conflicts = FALSE)

csv_files <- c(
  list.files(here::here("data", "colnames_exact"), full.names = TRUE),
  list.files(here::here("data", "colnames_positional"), full.names = TRUE),
  list.files(here::here("data", "colnames_other"), full.names = TRUE)
)
names(csv_files) <- tools::file_path_sans_ext(basename(csv_files))

col_types <- cols(
  name = col_character(),
  code = col_character(),
  description = col_character(),
  type = col_character()
)

d <- purrr::map_dfr(csv_files, read_csv, col_types = col_types, .id = "id")
```

コードリストは、2つタイプがある。
そのページに直接列挙されているタイプと、リンク先に詳細があるタイプ。
リンク先に詳細があるタイプは、`html_table()`を使った時点で失われてしまうので、別途収集する。

```{r kable}
d %>%
  filter(codelist) %>%
  arrange(code) %>% 
  transmute(
    id, 
    code, 
    type = str_squish(type),
    codelist_type = case_when(
      str_detect(type, "都道府県コード") ~ "PrefCd",
      str_detect(type, "行政コード") ~ "AdminAreaCd",
      # A22
      str_detect(type, "豪雪区分コード") ~ "GosetsuCd",
      # A22-mA
      str_detect(type, "集計単位フラグ") ~ "AggregateUnitFlag",
      str_detect(type, "位置特定レベル") ~ "PosSpecificLevel",
      # A29
      str_detect(type, "用途地域分類コード") ~ "UseDistrictCd",
      # A31
      str_detect(type, "浸水深ランクコード") ~ "water_depth_code",
      str_detect(type, "浸水継続時間ランクコード") ~ "flood_duration_code",
      str_detect(type, "危険区域区分コード") ~ "hazardous_area_classification_code",
      # A33
      str_detect(type, "現象種別コード") ~ "CodeOfPhenomenon",
      str_detect(type, "区域コード") ~ "CodeOfZone_h27",       # v1.1 では CodeOfZone が使われている
      str_detect(type, "特別警戒区域未指定コード") ~ "CodeOfUnSpecification",
      
      # TODO
      
      code %in% c("G04a_005", "G04a_005", "G04d_005") ~ "undersea",
      code %in% c("G04a_007", "G04a_009","G04c_007","G04c_009","G04d_007","G04d_009") ~ "direction",
      code == "A15_003" ~ "authority_type",
      code == "A15_004" ~ "protection_area_type",
      code == "P13_009" ~ "urban_planning_decided",
      code == "P15_017" ~ "industrial_waste_disposal",
      code == "P15_018" ~ "industrial_waste_special_treatment",
      code == "P17_003" ~ "firehouse_type",
      code == "P21A_003" ~ "water_supply_type",
      code == "P24_011" ~ "refereced_from_agri",
    )
  ) %>%
  knitr::kable()
```

## 直接列挙してるやつ

```{r out_dir}
out_dir <- here::here("data", "codelist")
dir.create(out_dir, showWarnings = FALSE)
```


### `G04a_005`, `G04a_005`, `G04d_005`

```{r G04a_005}
d %>% 
  filter(str_detect(type, "海面下"))

tibble(
  code  = c("0", "5", "unknown"),
  label = c("その他", "海面下", NA)
) %>% 
  readr::write_csv(file.path(out_dir, "undersea.csv"))
```

### `G04a_007`, `G04a_009`,`G04c_007`,`G04c_009`,`G04d_007`,`G04d_009`

```{r G04a_007}
d %>% 
  filter(str_detect(type, "方向なし"))

tibble(
  code  = c(as.character(0:8), "unknown"),
  label = c("方向なし", "北", "北東", "東", "東南", "南", "南西", "西", "北西", NA)
) %>% 
  readr::write_csv(file.path(out_dir, "direction.csv"))
```

### `A15_003`

```{r A15_003}
d %>% 
  filter(str_detect(type, "指定機関コード"))

tibble(
  code  = c("1", "2"),
  label = c("国指定", "県指定")
) %>% 
  readr::write_csv(file.path(out_dir, "authority_type.csv"))
```


### `A15_004`

```{r A15_004}
d %>% 
  filter(str_detect(type, "保護区分コード"))

tibble(
  code  = c("1", "2", "3", "4"),
  label = c("鳥獣保護区",　"特別保護地区", "休猟区", "特例休猟区")
) %>% 
  readr::write_csv(file.path(out_dir, "protection_area_type.csv"))
```


### `P13_009`

```{r P13_009}
d %>% 
  filter(str_detect(type, "都市計画決定"))

tibble(
  code  = c("0", "1", "2"),
  label = c("未確認", "決定", "未決定")
) %>% 
  readr::write_csv(file.path(out_dir, "urban_planning_decided.csv"))
```


### `P15_017`

```{r P15_017}
d %>% 
  filter(str_detect(type, "産廃施設コード"))

tibble(
  code  = c("1", "2"),
  label = c("中間処理施設", "最終処理施設")
) %>% 
  readr::write_csv(file.path(out_dir, "industrial_waste_disposal.csv"))
```


### `P15_018`

```{r P15_018}
d %>% 
  filter(str_detect(type, "特別管理コード"))

tibble(
  code  = c("0", "1"),
  label = c("特別管理産業廃棄物処理以外", "特別管理産業廃棄物処理")
) %>% 
  readr::write_csv(file.path(out_dir, "industrial_waste_special_treatment.csv"))
```

### `P17_003`

```{r P17_003}
d %>% 
  filter(str_detect(type, "消防本部"))

tibble(
  code  = c("1", "2", "3"),
  label = c("消防本部", "消防署", "分署・出張所")
) %>% 
  readr::write_csv(file.path(out_dir, "firehouse_type.csv"))
```

### `P21A_003`

```{r P21A_003}
d %>% 
  filter(str_detect(type, "簡易水道"))

tibble(
  code  = c("1", "2", "3"),
  label = c("上水道", "簡易水道（公営）", "簡易水道（非公営）")
) %>% 
  readr::write_csv(file.path(out_dir, "water_supply_type.csv"))
```

### `P24_011`

```{r P24_011}
d %>% 
  filter(str_detect(type, "グリーン・ツーリズムデータベース"))

tibble(
  code  = c("1", "2", "3"),
  label = c("グリーン・ツーリズムデータベース", "農業協同組合名鑑", "全国市民農園リスト")
) %>% 
  readr::write_csv(file.path(out_dir, "refereced_from_agri.csv"))
```
