---
title: "Validate codelist"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

codelistがカラムとマッチするか確認する

```{r check}
library(readr)
library(stringr)
library(dplyr, warn.conflicts = FALSE)

csv_files <- c(
  list.files(here::here("data", "colnames_exact"), full.names = TRUE),
  list.files(here::here("data", "colnames_positional"), full.names = TRUE),
  list.files(here::here("data", "colnames_other"), full.names = TRUE)
)
names(csv_files) <- tools::file_path_sans_ext(basename(csv_files))

col_types <- cols(
  name = col_character(),
  code = col_character(),
  description = col_character(),
  type = col_character()
)

d <- purrr::map_dfr(csv_files, read_csv, col_types = col_types, .id = "id")
```

いくつか重複があるので、`id`, `code`, `name`の組がユニークになるようにまとめなおす

```{r unique}
d %>%
  group_by(id, code, name) %>%
  filter(n() > 1) %>%
  knitr::kable()

d <- d %>% 
  group_by(id, code, name) %>% 
  summarise(
    across(.fns = first),
    .groups = "drop"
  )
```

個別対応したものは先に紐づける。ここで紐付かなかったものに対して、対応表を正規表現でマッチさせる。

```{r kable}
d %>%
  filter(codelist) %>%
  arrange(code) %>% 
  transmute(
    id, 
    code, 
    type = str_squish(type),
    codelist_type = case_when(
      code %in% c("G04a_005", "G04a_005", "G04d_005") ~ "undersea",
      code %in% c("G04a_007", "G04a_009","G04c_007","G04c_009","G04d_007","G04d_009") ~ "direction",
      code == "A15_003" ~ "authority_type",
      code == "A15_004" ~ "protection_area_type",
      code == "P13_009" ~ "urban_planning_decided",
      code == "P15_017" ~ "industrial_waste_disposal",
      code == "P15_018" ~ "industrial_waste_special_treatment",
      code == "P17_003" ~ "firehouse_type",
      code == "P21A_003" ~ "water_supply_type",
      code == "P24_011" ~ "refereced_from_agri",
      code == "L03b_c_002" ~ "tweak_LandUseCd",
    )
  ) %>%
  knitr::kable()
```


URLから取ってきた分を`d`に紐付ける。


```{r codelist}
d_codelist <- readr::read_csv(here::here("data", "codelist_list.csv"), col_types = "ccc")

# いくつか除外したやつもあるので、実際に存在するやつだけに絞り込む
codelist_existing <- fs::dir_ls(here::here("data", "codelist")) %>% 
  basename() %>% 
  tools::file_path_sans_ext()

# LandUseCd は年度によって微妙に違うので個別対応が必要、ここでは除外する
# SectionTypeCd/SectionCd も年度によって微妙に違うので個別対応が必要、ここでは除外する
exclude_pattern <- "^LandUseCd|^SectionTypeCd|^SectionCd"

d_codelist <- d_codelist %>% 
  filter(
    codelist_id %in% codelist_existing,
    !str_detect(codelist_id, exclude_pattern)
  ) %>% 
  rename(type_part = name)
```

```{r codelist_join}
d_joined <- d %>% 
  left_join(d_codelist, by = "id") %>% 
  mutate(matched = str_detect(type, fixed(type_part))) %>% 
  group_by(id, code, name) %>% 
  summarise(
    data = list(codelist_id[matched]),
    .groups = "drop"
  )
```
