---
title: "Extract data from C23"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r get_tables}
library(rvest)
library(dplyr, warn.conflicts = FALSE)

dir.create(here::here("data", "attrs"), recursive = TRUE, showWarnings = FALSE)

input <- here::here("data-raw", "datalist", "KsjTmplt-C23.html")
id <- stringr::str_replace(basename(input), "(?:KsjTmplt-)(.*?)(?:-v.*)?(?:\\.html)", "\\1")
output <- here::here("data", "attrs", glue::glue("{id}.csv"))

attr_table <- read_html(input) %>% 
  html_elements("table.tablelist tr") %>%
  purrr::keep(~ {
    html_text2(html_element(.x, "th")) == "属性情報" &&
      length(html_element(.x, "table")) > 0
  }) %>% 
  html_table()

stopifnot(length(attr_table) == 1)

knitr::kable(attr_table[[1]])

attr_table[[1]] %>% 
  filter(
    !stringr::str_detect(stringr::str_remove_all(属性の型, "\\s+"), "^(地物|曲?面型|曲?線型|点型|GM_Surface|GM_Curve|GM_Point)")
  ) %>%
  dplyr::transmute(
    name = 属性名,
    code = NA,
    description = 説明,
    type = 属性の型
  ) %>% 
  readr::write_csv(output)
```

